import { readState } from './lib.mjs';
import { readFileSync } from 'node:fs';
const BOT = 'email_9b295ef4019bfd69361b3151';
const s = readState(BOT);
// 游标的实际值
const cur = s.mailCursor;
console.log('  游标:', String(cur).slice(0,50));
console.log('  → 这是 #oldestFirst 反转后的【最后一封】（最新）');
console.log('');
console.log('  但列表按【最新在前】返回，下次轮询时：');
console.log('    第1封 = 最新（可能比游标更新）→ 收集');
console.log('    ...直到遇到游标 → 停止');
console.log('  若游标那封【已不在第一页】(26封 > 25 limit) → 永不命中 → 收集全部');
console.log('');
console.log('  === 实测：limit=25 时第 26 封是否够到 ===');
const { AgentMailTransport } = await import('../src/channels/email/transports/agent-mail.mjs');
const yaml = readFileSync('/home/duola/.dsh/.credentials.yaml','utf8');
const line = yaml.split('\n').find(l => l.includes('DSH_EMAIL_PASSWORD_9B295EF'));
const cred = JSON.parse(/:\s*'(.*)'\s*$/.exec(line)[1]);
const api = new AgentMailTransport({ config: cred });
const msgs = await api.listMessages({ afterUid: cur, limit: 25, allowSenders: new Set(['16991609@qq.com']) });
console.log('  返回:', msgs.length, '封（期望只返回比游标新的）');
for (const m of msgs.slice(0,3)) console.log('   -', String(m.uid).slice(0,30), '|', String(m.subject).slice(0,22));
